spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/detour
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  datasource.hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 10000
    max-lifetime: 1800000
    connection-timeout: 30000
  data:
    redis:
      auth:
        host: ${AUTH_REDIS_HOST} # Redis 인증 서버의 호스트(EC2와 연결)
        port: ${AUTH_REDIS_PORT} # Redis 인증 서버의 포트

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${SOCIAL_KAKAO_CLIENT_ID}
            client-secret: ${SOCIAL_KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
            redirect-uri: http://localhost:8081/api/users/login/oauth2/code/kakao
            client-name: Kakao
            provider: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id

  mail:
    host: smtp.gmail.com # Gmail의 SMTP 서버 주소
    port: 587 # Gmail의 SMTP 서버 포트
    username: detourOfficial0717@gmail.com
    password: ${APP_PASSWORD}
    properties:
      mail.smtp.auth: true # SMTP 인증 사용
      mail.smtp.starttls.enable: true # TLS 사용

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  access:
    token:
      expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh:
    token:
      expiration: ${REFRESH_TOKEN_EXPIRATION}

custom:
  admin-token: ${ADMIN_TOKEN}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

    region:
      static: ${AWS_REGION}
      auto: false

    stack:
      auto: false

    s3:
      bucket: ${AWS_BUCKET_NAME}


server:
  port: 8081