### 1-1-1. 회원가입 - USER_1
POST https://detourofficial.shop/api/users/signup
Content-Type: application/json

{
  "loginId" : "username1",
  "password" : "Password1!",
  "email" : "abc@naver.com",
  "nickname" : "bro-진창1",
  "isAdmin" : false
}

### 1-1-2. 회원가입 - USER_2
POST https://detourofficial.shop/api/users/signup
Content-Type: application/json

{
  "loginId" : "subong123",
  "password" : "Password1!",
  "email" : "def@naver.com",
  "nickname" : "subong",
  "isAdmin" : false
}

### 1-2. 회원가입 - ADMIN
POST https://detourofficial.shop/api/users/signup
Content-Type: application/json

{
  "loginId" : "username2",
  "password" : "Password2!",
  "email" : "abcd@naver.com",
  "nickname" : "창봉",
  "isAdmin" : true,
  "adminToken" : "{{ADMIN_TOKEN}}"
}

### 1-3-1. 아이디 중복확인 (이미 해당 아이디 존재 시 true 반환)
GET https://detourofficial.shop/api/users/check-loginId?loginId=username1
Content-Type: application/json

### 1-3-2. 닉네임 중복확인 (이미 해당 닉네임 존재 시 true 반환)
GET https://detourofficial.shop/api/users/check-nickname?nickname=subong
Content-Type: application/json

### 1-3-3. 이메일 중복확인 (이미 해당 이메일 존재 시 true 반환)
GET https://detourofficial.shop/api/users/check-email?email=abc@naver.com
Content-Type: application/json