### 10-1. 인증 이메일 전송
POST https://detourofficial.shopapi/users/send-certification
Content-Type: application/json
Authorization: {{access_token}}

{
  "email" : "chxngbro@gmail.com"
}

### 10-2. 이메일 인증 확인
GET https://detourofficial.shop/api/users/verify?certificationNumber=434586&email=chxngbro@gmail.com
Content-Type: application/json
Authorization: {{access_token}}