### 4-1. 일정 생성
POST http://localhost:8081/api/schedules
Content-Type: application/json
Authorization: {{access_token}}

{
  "title": "일정 1",
  "departureDate" : "2024-07-22",
  "arrivalDate" : "2024-07-26"
}

### 4-2-1. 해당 일정에 대한 일행 초대
POST http://localhost:8081/api/schedules/1/invitation
Content-Type: application/json
Authorization: {{access_token}}

{
  "nickname" : "subong"
}

### 4-2-2. 초대할 아이디가 존재하지 않는 사용자인 경우
POST http://localhost:8081/api/schedules/1/invitation
Content-Type: application/json
Authorization: {{access_token}}

{
  "nickname" : "subongbong"
}

### 4-3. 일행 초대 취소
DELETE http://localhost:8081/api/schedules/1/invitation
Content-Type: application/json
Authorization: {{access_token}}

{
  "nickname" : "subong"
}

### 4-4. 일정 좋아요 등록
POST http://localhost:8081/api/schedules/1/likes
Content-Type: application/json
Authorization: {{access_token}}

### 4-5. 일정 좋아요 취소
DELETE http://localhost:8081/api/schedules/likes/2
Content-Type: application/json
Authorization: {{access_token}}
