### 4-1. 일정 생성
POST http://localhost:8081/api/schedules
Content-Type: application/json
Authorization: {{access_token}}

{
  "title": "일정 1",
  "departureDate" : "2024-07-22",
  "arrivalDate" : "2024-07-26"
}
