### 6-1. 마커 생성
POST http://localhost:8081/api/dailPlan/{dailPlanId}/markers/{placeId}
Content-Type: application/json
Authorization: {{access_token}}

{
  "latitude" : "35.927848",
  "longitude" : "127.063731"
}

### 6-2. 마커 전체조회
POST http://localhost:8081/api/dailPlan/{dailyPlanId}/markers
Content-Type: application/json
Authorization: {{access_token}}

### 6-3. 마커 단건 조회
POST http://localhost:8081/api/dailPlan/{dailyPlanId}/markers/{markerId}
Content-Type: application/json
Authorization: {{access_token}}

### 6-4. 마커 글 저장
POST http://localhost:8081/api/dailyPlans/markers/{markerId}/content
Content-Type: application/json
Authorization: {{access_token}}

{
  "content" : "오늘 재미있었어요"
}

### 6-5. 마커 글 수정
POST http://localhost:8081/api/dailyPlans/markers/{markerId}/content
Content-Type: application/json
Authorization: {{access_token}}

{
  "content" : "신나는 하루"
}

### 6-6. 마커 삭제
POST http://localhost:8081/api/dailyPlans/markers/{markerId}
Content-Type: application/json
Authorization: {{access_token}}