### 5-1. 데일리플랜 생성
POST http://localhost:8081/api/schedules/1/daily-plans
Content-Type: application/json
Authorization: {{access_token}}

{
  "day": 1
}

### 5-2. 해당 Schedule에 대한 DailyPlan 목록 조회
GET http://localhost:8081/api/schedules/1/daily-plans
Content-Type: application/json
Authorization: {{access_token}}