### 6-1. 마커 생성
POST http://localhost:8081/api/daily-plans/1/place/1/markers
Content-Type: application/json
Authorization: {{access_token}}

{
  "latitude" : 35.927848,
  "longitude" : 127.063731
}

### 6-2. 마커 전체조회
GET http://localhost:8081/api/daily-plans/1/markers
Content-Type: application/json
Authorization: {{access_token}}

### 6-3. 마커 단건 조회
GET http://localhost:8081/api/daily-plans/1/markers/1
Content-Type: application/json
Authorization: {{access_token}}

### 6-4. 마커 글 저장
POST http://localhost:8081/api/daily-plans/markers/1/content
Content-Type: application/json
Authorization: {{access_token}}

{
  "content" : "오늘 재미있었어요"
}

### 6-5. 마커 글 수정
PATCH http://localhost:8081/api/daily-plans/markers/4/content
Content-Type: application/json
Authorization: {{access_token}}

{
  "content" : "신나는 하루"
}

### 6-6. 마커 삭제
DELETE http://localhost:8081/api/daily-plans/markers/5
Content-Type: application/json
Authorization: {{access_token}}

### 6-7. 마커 사진 등록 -> POSTMAN 이용


### 6-8. 마커 파일 삭제
DELETE http://localhost:8081/api/daily-plans/markers/1/files?fileUrl=https://detour1.s3.ap-northeast-2.amazonaws.com/73942e29-654f-4a0e-a6f4-5688d5696c75.mp4
Content-Type: application/json
Authorization: {{access_token}}

### 6-9. 위도, 경도 조회
GET http://localhost:8081/api/daily-plans/markers/1/location
Content-Type: application/json
Authorization: {{access_token}}
