### 7-1. 프로필 조회
GET http://52.78.2.148:80/api/users/profile
Content-Type: application/json
Authorization: {{access_token}}

#### 7-2. 닉네임 수정
PATCH http://52.78.2.148:80/api/users/profiles/nickname
Content-Type: application/json
Authorization: {{access_token}}

{
  "nickname" : "창브로"
}

#### 7-3. 이메일 수정
PATCH http://52.78.2.148:80/api/users/profiles/email
Content-Type: application/json
Authorization: {{access_token}}

{
  "email" : "shlee509@nate.com"
}

#### 7-4. 비밀번호 수정
PATCH http://52.78.2.148:80/api/users/profiles/password
Content-Type: application/json
Authorization: {{access_token}}

{
  "password": "Password1!",
  "newPassword": "Password2!",
  "confirmNewPassword": "Password3!"
}